spring:
  datasource:
    initialization-mode: always
    schema: classpath:data.sql

    url: jdbc:postgresql://localhost:5432/postgres
    username: postgress
    password: roott

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true





    initialization-mode: always
    schema: classpath:data.sql
